<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\AccountStatus\Queries\**" />
    <Compile Remove="Features\Authentication\Queries\**" />
    <Compile Remove="Features\Identity\Queries\**" />
    <Compile Remove="Features\RoleManagement\Queries\**" />
    <EmbeddedResource Remove="Features\AccountStatus\Queries\**" />
    <EmbeddedResource Remove="Features\Authentication\Queries\**" />
    <EmbeddedResource Remove="Features\Identity\Queries\**" />
    <EmbeddedResource Remove="Features\RoleManagement\Queries\**" />
    <None Remove="Features\AccountStatus\Queries\**" />
    <None Remove="Features\Authentication\Queries\**" />
    <None Remove="Features\Identity\Queries\**" />
    <None Remove="Features\RoleManagement\Queries\**" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="11.11.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.17" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Identity.Domain\Identity.Domain.csproj" />
	</ItemGroup>


</Project>
